<!-- CLASSIFICAÇÃO_bancoEsperanca_FLAI_csv -->
<!-- # Desafio:
<!-- ajudar o Banco Esperança e o Sr. Cauteloso a construir o cérebro do Previsor, de forma a maximizar os ganhos de moedas de ouro! -->
<!-- data prevista para deadline: 27/03/2024 -->

In [2]:
# Desafio
# ajudar o Banco Esperança e o Sr. Cauteloso a construir o cérebro do Previsor, de forma a maximizar os ganhos de moedas de ouro!

# variável alvo
# status_do_emprestimo: empréstimo foi pago ou não

In [3]:
# Import libs
import pandas as pd

In [ ]:
# fonte de dados
# https://flavia-flai.streamlit.app/Competi%C3%A7%C3%B5es_FLAI
df_train = pd.read_csv('treino.csv')
df_test = pd.read_csv('teste.csv')

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   montante_financiado       10000 non-null  float64
 1   prazo                     10000 non-null  object
 2   taxa_de_juros             10000 non-null  object
 3   parcela                   10000 non-null  float64
 4   tempo_de_emprego          9696 non-null   object
 5   propriedade_de_casa       10000 non-null  object
 6   renda_anual               9999 non-null   float64
 7   status_de_verificacao     10000 non-null  object
 8   status_do_emprestimo      10000 non-null  object
 9   finalidade                10000 non-null  object
 10  divida_sobre_renda        10000 non-null  object
 11  inadimplencias_2_anos     10000 non-null  int64
 12  score_de_credito          9999 non-null   float64
 13  numero_de_dependentes     10000 non-null  int64
 14  anos_na_residencia_atual  10000 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 1.1+ MB

In [9]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   montante_financiado       4000 non-null   float64
 1   prazo                     4000 non-null   object
 2   taxa_de_juros             4000 non-null   object
 3   parcela                   4000 non-null   float64
 4   tempo_de_emprego          3888 non-null   object
 5   propriedade_de_casa       4000 non-null   object
 6   renda_anual               4000 non-null   float64
 7   status_de_verificacao     4000 non-null   object
 8   finalidade                4000 non-null   object
 9   divida_sobre_renda        4000 non-null   object
 10  inadimplencias_2_anos     4000 non-null   int64
 11  score_de_credito          4000 non-null   float64
 12  numero_de_dependentes     4000 non-null   int64
 13  anos_na_residencia_atual  4000 non-null   int64
dtypes: float64(4), int64(3), object(7)
memory usage: 437.6+ KB

In [14]:
df_train.tail().T

,9995,9996,9997,9998,9999
montante_financiado,19466.0,7549.0,3422.0,13308.0,9444.0
prazo,Curto,Curto,Curto,Longo,Curto
taxa_de_juros,7.9%,14.3%,11.8%,7.9%,11.7%
parcela,619.54,265.19,122.36,272.44,319.48
tempo_de_emprego,mais de 10 anos,mais de 10 anos,1 ano,7 anos,1 ano
propriedade_de_casa,Empréstimo,Alugado,Alugado,Empréstimo,Alugado
renda_anual,70000.0,41400.0,93000.0,27000.0,33000.0
status_de_verificacao,Fonte Verificada,Não Verificado,Não Verificado,Verificado,Fonte Verificada
status_do_emprestimo,Pago,Não Pago,Não Pago,Pago,Não Pago
finalidade,Consolidação de Dívida,Outro,Outro,Consolidação de Dívida,Consolidação de Dívida
divida_sobre_renda,13.8%,23.8%,4.3%,26.9%,19.9%
inadimplencias_2_anos,0,1,0,0,0
score_de_credito,449.730968,482.825254,285.263535,430.865734,461.265534
numero_de_dependentes,1,1,1,2,0
anos_na_residencia_atual,5,7,6,8,12

In [19]:
df_test.tail().T

,3995,3996,3997,3998,3999
montante_financiado,6260.0,10040.0,3081.0,24024.0,24866.0
prazo,Longo,Curto,Curto,Curto,Curto
taxa_de_juros,9.2%,7.9%,16.5%,16.4%,14.7%
parcela,137.13,320.28,115.18,849.89,869.32
tempo_de_emprego,3 anos,5 anos,5 anos,2 anos,menos de 1 ano
propriedade_de_casa,Alugado,Empréstimo,Alugado,Empréstimo,Alugado
renda_anual,35000.0,106000.0,61000.0,148000.0,88000.0
status_de_verificacao,Não Verificado,Verificado,Fonte Verificada,Não Verificado,Não Verificado
finalidade,Consolidação de Dívida,Consolidação de Dívida,Consolidação de Dívida,Pequena Empresa,Pequena Empresa
divida_sobre_renda,23.5%,12.3%,14.0%,14.4%,5.8%
inadimplencias_2_anos,0,0,0,0,0
score_de_credito,354.398801,294.129768,401.131268,487.928369,428.930368
numero_de_dependentes,0,5,0,2,1
anos_na_residencia_atual,4,12,7,3,7

In [18]:
df_train.isnull().sum()

montante_financiado           0
prazo                         0
taxa_de_juros                 0
parcela                       0
tempo_de_emprego            304
propriedade_de_casa           0
renda_anual                   1
status_de_verificacao         0
status_do_emprestimo          0
finalidade                    0
divida_sobre_renda            0
inadimplencias_2_anos         0
score_de_credito              1
numero_de_dependentes         0
anos_na_residencia_atual      0
dtype: int64

In [20]:
df_test.isnull().sum()

montante_financiado           0
prazo                         0
taxa_de_juros                 0
parcela                       0
tempo_de_emprego            112
propriedade_de_casa           0
renda_anual                   0
status_de_verificacao         0
finalidade                    0
divida_sobre_renda            0
inadimplencias_2_anos         0
score_de_credito              0
numero_de_dependentes         0
anos_na_residencia_atual      0
dtype: int64